kuring-160 업데이트 권유 dialog 추가
ku-ring/KU-Ring-Android pull request #151
Opened 2024-04-10 08:03 UTC by mwy3055

https://kuring.atlassian.net/browse/KURING-160?atlOrigin=eyJpIjoiZDA4ODI4YWMxYWIyNDYwZmIxM2I4ZWU2MGJlNmQ1ODYiLCJwIjoiaiJ9

## 요약

앱 버전이 [최소 버전](https://[raw.githubusercontent.com/ku-ring/space/main/app-versions/android.json](https://raw.githubusercontent.com/ku-ring/space/main/app-versions/android.json))보다 낮을 경우, 업데이트를 권유하는 Dialog를 보여줍니다.

`업데이트` 버튼을 누르면 쿠링 play store로 이동하고, `무시하기`를 누르면 온보딩 또는 메인 화면으로 이동합니다.

| 최소 버전 로딩중 | 업데이트 권유 Dialog |
| --- | --- |
|![image](https://github.com/ku-ring/KU-Ring-Android/assets/45386920/6613a411-57ce-434b-bda6-5b3dba776de6)| ![image](https://github.com/ku-ring/KU-Ring-Android/assets/45386920/a7040206-74ef-41eb-a796-abb1e8b1c603)|

## 작업 상세

* [쿠링스페이스](https://github.com/ku-ring/space) 데이터를 담당하는 `:data:space` 모듈을 추가했고, `KuringSpaceRepository(Impl)`을 구현했습니다.
* Retrofit API는 기존 `:data:remote:` 모듈에 추가했습니다.
* 스플래시 화면의 로직을 담당하는 `SplashViewModel`을 추가했습니다.
* 앱 버전을 로딩중일 때 보여줄 `CircularProgressIndicator`와, 업데이트 dialog인 `UpdateAppDialog`를 추가했습니다.

2024-04-10 09:36 UTC, x-0o0 commented on feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashActivity.kt
> +            delay(500)
딜레이 500 거는 이유는 뭔가요~?

2024-04-10 09:39 UTC, x-0o0 commented on feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashViewModel.kt
> +        return currentVersion < minimumVersion
오? "2.0.0" < "2.0.9" 이런 식으로 버전을 string 비교로 가능한가요~?

2024-04-10 09:41 UTC, x-0o0 approved these changes
LGTM

2024-04-10 09:50 UTC, l2hyunwoo requested changes
일단 잘 읽어봤습니다...!! 염려되는 부분들이 있어서 코멘트 남기니 확인 부탁드립니다.

2024-04-10 09:50 UTC, l2hyunwoo commented on data/space/src/main/java/com/ku_stacks/ku_ring/space/repository/KuringSpaceRepositoryImpl.kt
> +    }
현재 레트로핏에서 데이터를 들고 올때에는 suspend 함수를 통해서 데이터가 자체 비동기로 처리되어서 들어올텐데요. 이때 suspend modifier가 붙은 함수들은 레트로핏이 자체적으로 내부에서 enqueue를 사용하여 데이터가 올때까지 suspend하고 있다가 오면 데이터를 넘겨주는 방식으로 구현되어있습니다. 이를 자세히 알고 싶으시다면 suspendCancellableCoroutines를 좀 잘 파보시면 좋을 것 같은데요.

요를 말하면, enqueue 자체에서 백그라운드 스레드를 활용하여 데이터를 들고 오기때문에 추가적으로 ioDispatcher로 스레드 전환을 할 필요가 없습니다. 오히려 컨텍스트 스위칭 N번 일어나서 비효율적일 것 같네요

참고 - [Retofit2 내부에서의 스케줄러 처리](https://thdev.tech/kotlin/2021/01/12/Retrofit-Coroutines/)

2024-04-10 09:50 UTC, l2hyunwoo commented on data/space/build.gradle
data space 모듈을 추가적으로 만드신 이유가 있을까요....?

2024-04-10 09:50 UTC, l2hyunwoo commented on feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashActivity.kt
> +        }
지금과 같이 구현을 하시면 화면이 백그라운드로 가도 Flow가 구독될 수 있는 여지가 있습니다. repeatOnLifecycle을 활용하시거나 flowWithLifecycle 사용하면 좋을 것 같네요.

[Safer way to collect flows from Android UIs](https://medium.com/androiddevelopers/a-safer-way-to-collect-flows-from-android-uis-23080b1f8bda)

2024-04-10 09:50 UTC, l2hyunwoo commented on settings.gradle
> +include ':data:space'
위의 형식처럼 바꿔주세요!

2024-04-10 09:50 UTC, l2hyunwoo commented on feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashScreenState.kt
👍🏻 좋은 도식화 감사합니다.

2024-04-10 09:50 UTC, l2hyunwoo commented on feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashViewModel.kt
> +        get() = _splashScreenState
```suggestion
    val splashScreenState: StateFlow<SplashScreenState> = _splashScreenState.asStateFlow()
```

별반 차이없을 수 있지만 MutableStateFlow를 ReadonlyStateFlow로 변환해준다는 점에서 의미가 있어보이네요.

> ReadOnlyStateFlow 의 계층을 따라가면 emit 을 가지는 Interface를 구현하지 않는다. 따라서 asStateFlow 로 하면 어떤 형변환을 해도 값을 발행 할 수 없다. 외부에서 값 발행을 반드시 제한해야 하는 경우 적절하다

```kotlin
public fun <T> MutableStateFlow<T>.asStateFlow(): StateFlow<T> =
    ReadonlyStateFlow(this, null)
```


[참고](https://medium.com/@equipment_room/kotlin-mutableshared-stateflow-to-shard-stateflow-984f69989d57)

2024-04-10 09:50 UTC, l2hyunwoo commented on feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashViewModel.kt
> +        }
예외처리 안하시나요?

2024-04-10 09:50 UTC, l2hyunwoo commented on feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashActivity.kt
> +                val screenState by viewModel.splashScreenState.collectAsState()
```suggestion
                val screenState by viewModel.splashScreenState.collectAsStateWithLifecycle()
```

2024-04-10 09:50 UTC, l2hyunwoo commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/space/KuringSpaceClient.kt
> +class KuringSpaceClient @Inject constructor(private val kuringSpaceService: KuringSpaceService) {
다른 오픈소스 안드로이드 프로젝트 들어가보면 Client라는 말보단 DataSource라는 네이밍을 더 많이 가져가는 것 같아요

Service <- DataSource <- Repository <- ViewModel <- Screen

이런식?

2024-04-10 09:56 UTC, l2hyunwoo commented on feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashActivity.kt
> +            delay(500)
서버통신이 빠르게 되는 경우에는 로딩인티케이터가 잠깐 보여지고 지나가게 되는데요, 이때 로딩 인디케이터는 사용자 경험에 있어서 "왜 깜빡이는 거지" 정도의 존재로 남게되고 사용자에게 부정적인 경험을 줄 여지가 있습니다. 그래서 로딩인디케이터를 확실하게 보여주려고 하는 것 같은데요 맞을까요? @mwy3055

2024-04-10 10:05 UTC, l2hyunwoo commented on feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashViewModel.kt
> +        return currentVersion < minimumVersion
어라...이거 왜 되나요? 혹시 이거 테스트 코드 작성 가능하실까요?

2024-04-10 10:08 UTC, mwy3055 commented on feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashViewModel.kt
> +        return currentVersion < minimumVersion
집가서 짜볼게요

2024-04-10 10:36 UTC, yeon-kyu commented on feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashActivity.kt
> +        lifecycleScope.launch(Dispatchers.Default) {
Default Dispatcher로 하신 이유가 있을까요?

2024-04-10 12:32 UTC, yeon-kyu commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/space/KuringSpaceClient.kt
> +class KuringSpaceClient @Inject constructor(private val kuringSpaceService: KuringSpaceService) {
아직 저희끼리 정하지 않은것같은데 이참에 논의해서 컨벤션으로 가져가면 좋을것같아요

Service 는 개인적으로 혼용되는 네이밍이라 생각해서(android의 컴포넌트이기도하고) 선호하진 않는데 아래 네이밍에 한표입니다
api <- DataSource(만들지는 각자 판단. 저는 잘안만들듯) <- Repository <- ViewModel <- Screen

2024-04-10 15:15 UTC, l2hyunwoo commented on data/space/src/main/java/com/ku_stacks/ku_ring/space/repository/KuringSpaceRepositoryImpl.kt
> +    }
정확한 이해십니다. 저도 Room은 withContext로 디스패쳐 설정합니다.

2024-04-10 15:15 UTC, mwy3055 commented on data/space/src/main/java/com/ku_stacks/ku_ring/space/repository/KuringSpaceRepositoryImpl.kt
> +    }
https://github.com/ku-ring/KU-Ring-Android/pull/151/commits/3e64fd33377df793c2ccdae0fee5f5ddf09ce947 에서 수정했습니다

2024-04-11 02:24 UTC, mwy3055 commented on data/space/build.gradle
최소 버전 API를 넣을 만한 data 모듈이 없다고 생각했습니다. `:data:user`에 넣을까 했는데, 앱 버전 API와 사용자 API에 딱히 공통점이 없다고 생각했어요

2024-04-11 02:47 UTC, mwy3055 commented on feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashActivity.kt
> +        }
정정 감사합니다. https://github.com/ku-ring/KU-Ring-Android/pull/151/commits/9b307b314efb789287b0ffa5a13698b2fe6bd4ca 에서 수정했어요

2024-04-11 02:48 UTC, mwy3055 commented on feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashActivity.kt
> +                val screenState by viewModel.splashScreenState.collectAsState()
https://github.com/ku-ring/KU-Ring-Android/pull/151/commits/9b307b314efb789287b0ffa5a13698b2fe6bd4ca 에서 수정했습니다. 

`lifecycle-runtime-compose`가 선언은 되어있는데, 의존성 번들에 없더라고요;;

2024-04-11 02:49 UTC, mwy3055 commented on settings.gradle
> +include ':data:space'
https://github.com/ku-ring/KU-Ring-Android/pull/151/commits/e7d80da9d35ae4283fc52ee45be406ecd4de67ec 에서 수정했습니다

2024-04-11 02:57 UTC, mwy3055 commented on feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashViewModel.kt
> +        get() = _splashScreenState
큰 차이는 없는 것 같지만, 습관으로 해두기 좋아보이네요. `StateFlow`를 다시 `MutableStateFlow`로 변환하는 발상은 (안티패턴이긴 하지만) 처음 봤네요;;

https://github.com/ku-ring/KU-Ring-Android/pull/151/commits/193950ad2313a2e862b08373851ecdd4d1cd1b16 에서 수정했습니다.

2024-04-11 04:45 UTC, mwy3055 commented on feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashViewModel.kt
> +        }
> @mwy3055는 안 합니다. 쿠링은 합니다

https://github.com/ku-ring/KU-Ring-Android/pull/151/commits/ff12a53189870b59b0bf50bf11609e3635f8b298 에서 예외 처리 코드를 추가했습니다. `KuringSpaceRepositoryImpl`에서 예외가 발생하면 `0.0.0`을 반환하는 catch 구문을 작성했습니다.

2024-04-11 05:02 UTC, mwy3055 commented on feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashViewModel.kt
> +        return currentVersion < minimumVersion
검증 결과, 몇몇 케이스에서 오류가 있습니다. 중요한 로직 코드를 검증하지 않고 push한 점에 대해서는 사과의 말씀을 드립니다.

* `2.0.0` < `2.0.1`: 정상 판별
* `1.10.1` < `2.0.0`: 정상 판별
* `9.9.9` < `10.0.0`: **정상 판별 불가**

https://github.com/ku-ring/KU-Ring-Android/pull/151/commits/08794cd9afa1037a2bc022928a9fd9cab86d1da2 에서 현우님께서 추천하신 오픈소스 [SemVer(Semantic Version)](https://github.com/swiftzer/semver) 를 사용하여 비교하도록 수정했고, 테스트 코드도 추가했습니다.

2024-04-11 05:07 UTC, mwy3055 commented on feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashActivity.kt
> +        lifecycleScope.launch(Dispatchers.Default) {
팝업을 무시하고 메인 화면으로 이동할 때, 팝업이 부드럽게 사라지지 않고 버벅이다가 화면이 전환되는 문제가 있었어서 Main dispatcher가 문제인가 의심했기 때문입니다. 

다만 실제로는 화면이 너무 빨리 전환되는 것이 문제였고, 화면 전환 전후에 `delay(500)`을 사용하여 해결했습니다. 그런데 문제 해결 후에도 원래대로 돌려놓지 않았네요.

https://github.com/ku-ring/KU-Ring-Android/pull/151/commits/06c00a32f409f5827505e0e3bf1de53d0bd1f725 에서 `Dispatchers.Default`를 제거했습니다.

2024-04-11 05:17 UTC, mwy3055 commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/space/KuringSpaceClient.kt
> +class KuringSpaceClient @Inject constructor(private val kuringSpaceService: KuringSpaceService) {
저도 Retrofit이 data source의 역할을 수행할 수 있다고 생각합니다. 마찬가지로 로컬 data source는 Room DAO로 대체할 수 있다고 생각해요

따라서 현재 구현된 `...Client`와 `...Service`는 사용하지 않는 것을 제안합니다. 대략 정리하면 다음과 같습니다

* Screen
* ViewModel
* Repository(Impl)
* DataSource 또는 Mediator
  * (일반) 페이징이 필요하지 않은 경우: Retrofit(원격), Room DAO(로컬)
  * (특수) 원격 페이징이 필요할 경우: `RemoteMediator` 사용 (`DepartmentNoticeMediator` 참고)

2024-04-11 11:25 UTC, l2hyunwoo approved these changes
👍🏻

2024-04-11 11:40 UTC, merged

2024-04-12 08:19 UTC, yeon-kyu commented on feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashActivity.kt
> +        lifecycleScope.launch(Dispatchers.Default) {
이제서야 봤네요 🙏
Main 에서 collect하는것이 맞는것아 여쭤봤어요. 수정 감사합니다~!