kuring-168 KuringRoute의 companion object 인터페이스 정의
ku-ring/KU-Ring-Android pull request #274
Opened 2024-07-16 13:08 UTC by mwy3055

https://kuring.atlassian.net/browse/KURING-168?atlOrigin=eyJpIjoiZjY2YTczMzQ0MDcwNDljMzgyOGIyZDUwNDZiODM3ZDIiLCJwIjoiaiJ9

## PR 요약

``MainScreenRoute.Companion``에서 entry를 찾는 코드를 인터페이스로 정의하여 다른 route 클래스에서 재사용할 수 있도록 수정했습니다.

자꾸 똑같은 커밋 올려서 죄송합니다. 근데 이게 한번에 안 떠올라서 ㅠㅠ

2024-07-22 12:53 UTC, yeon-kyu requested changes
ㅗ누가 코드를 이렇게 짜요?

2024-07-22 12:58 UTC, x-0o0 commented
> 길치가 아니긴지

너무하심

2024-07-22 13:11 UTC, l2hyunwoo commented
> 길치가 아니긴지 

ㅠㅠ 너무행

2024-07-22 13:11 UTC, l2hyunwoo requested changes
그런김에 Request Change~

2024-07-23 01:49 UTC, mwy3055 commented
지도 보는 방법을 배우고 오겠습니다

2024-07-23 01:49 UTC, closed without merging

2024-07-23 03:34 UTC, x-0o0 commented
> 지도 보는 방법을 배우고 오겠습니다

나침반 빌려드려요?