kuring-187 쿠링봇 API, Room DB 구현
ku-ring/KU-Ring-Android pull request #277
Opened 2024-07-24 12:30 UTC by mwy3055

https://kuring.atlassian.net/browse/KURING-187?atlOrigin=eyJpIjoiZDYxYjQ1YjIyMjU3NGY5NDllZjllZGFjZDUzMjM3NzciLCJwIjoiaiJ9

## 쿠링봇 SSE data source 구현

Ktor를 활용하여 SSE data source를 구현하였습니다. SSE 스트림을 ``Flow<String>``으로 반환합니다. 스트림을 열지 못한 경우(연결 오류, 질문 횟수 초과 등) ``null``을 반환합니다.

그런데 Ktor 정식 출시 버전에서는 SSE를 지원하지 않고, 3.0.0-beta-1 버전부터 지원합니다. 베타 버전이라 좀 걱정되긴 하는데...

## 쿠링봇 로컬 DB 구현

쿠링봇 데이터를 저장할 Room entity와 Dao를 정의했습니다.

Entity의 필드는 다음과 같습니다.
* `id: Int`: PK, auto increment
* `message: String`: 질문 또는 응답 메시지
* `postedEpochSeconds: Long`: 질문 또는 응답이 생성된 시간
* `isQuery: Boolean`: 질문 여부를 저장하는 필드. `true`이면 질문, `false`이면 응답

Dao에 구현된 함수는 [이 커밋](https://github.com/ku-ring/KU-Ring-Android/commit/ad228a9b053684d0951b3761fe5a689cd8d5cd53)을 참고해 주세요.

## 앞으로 할 일
_비즈니스 로직_
* `AIRepository`, `AIRepositoryImpl` 정의
* `AIRepositoryImpl`을 inject하는 hilt 모듈 작성

_UI_
* `:feature:kuringbot` 모듈 생성
* `KuringBotViewModel` 작성
* `KuringBotScreen` 작성

2024-07-24 13:03 UTC, l2hyunwoo requested changes
확인 부탁드립니다.

2024-07-24 13:03 UTC, l2hyunwoo commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/sse/SSEDataSource.kt
> +}
```suggestion
interface SSEDataSource {
    /**
     * 쿠링봇 SSE 세션을 열고, [Flow] 포맷으로 반환한다.
     *
     * @param query 질문 내용
     * @param token 사용자 FCM 토큰
     *
     * @return 세션을 정상적으로 연 경우 non-null [Flow], 오류가 발생한 경우 null
     */
    fun openKuringBotSSESession(
        query: String,
        token: String,
    ): Flow<String>?
}
```

이 점 참고해주세요!

<img width="751" alt="스크린샷 2024-07-24 오후 10 01 49" src="https://github.com/user-attachments/assets/d6595035-f13b-412f-9ae5-4a3032b78fec">

2024-07-24 13:03 UTC, l2hyunwoo commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/sse/SSERemoteDataSource.kt
> +    }
```suggestion
    override fun openKuringBotSSESession(query: String, token: String): Flow<String>? {
        return try {
            tryOpenKuringBotSSESession(query, token)
        } catch (e: Throwable) {
            null
        }
    }

    private fun tryOpenKuringBotSSESession(query: String, token: String): Flow<String> {
        val url = BuildConfig.API_BASE_URL + "v2/ai/messages"
        return client.sseSession(urlString = url) {
            parameter("question", query)
            header("User-Token", token)
            header("Accept", "text/event-stream")
            header("Cache-Control", "no-cache")
        }.incoming.map { it.data.orEmpty() }
    }
```

2024-07-24 13:03 UTC, l2hyunwoo commented on data/remote/src/test/java/com/ku_stacks/ku_ring/remote/SSERemoteDataSourceTest.kt
> +    }
이거 테스트 결과가 어떻게 나오나요ㅋㅋㅋㅋ

2024-07-24 13:03 UTC, l2hyunwoo commented on data/remote/src/test/java/com/ku_stacks/ku_ring/remote/SSERemoteDataSourceTest.kt
> +        println("response: $response")
```suggestion
        // when
        val session = sseDataSource.openKuringBotSSESession(query, testToken)
        val response = session?.reduce { accumulator, value -> accumulator + value }
```

println 필요없을 것 같아요?

2024-07-24 13:41 UTC, mwy3055 commented on data/remote/src/test/java/com/ku_stacks/ku_ring/remote/SSERemoteDataSourceTest.kt
> +    }
디버그 서버에서는 쿼리와 상관없이 같은 답변을 보냅니다. 출력 결과는 다음과 같습니다.

```
response: 학생복지처장학복지팀의전화번호는02-450-3211~2이며,건국사랑/장학사정관장학/기금장학과관련된문의는02-450-3967로하시면됩니다.

2024-07-24 13:42 UTC, mwy3055 commented on data/remote/src/test/java/com/ku_stacks/ku_ring/remote/SSERemoteDataSourceTest.kt
> +        println("response: $response")
그렇습니다. 사실 직접 돌려보시라고 추가한 거긴 한데 ㅋㅋ

2024-07-24 13:53 UTC, mwy3055 commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/sse/SSEDataSource.kt
> +}
## 원인 설명

먼저 `suspend`가 붙은 이유를 말씀드리면, ktor의 sse 함수가 모두 suspend입니다. 단순히 세션을 열고 반환하는 `sseSession()`과, 세션에서 `block`을 실행하는 `sse()` 모두 suspend입니다.

![image](https://github.com/user-attachments/assets/53301bcf-3140-45df-a04a-57dd787adb1c)

제가 의도했던 로직은
1. `SSEDataStore`에서 SSE 스트림을 `Flow<String>`으로 반환
2. `SSERepository`에서 빈 문자열을 공백으로 치환하는 `Flow<String>`을 반환
3. `KuringBotViewModel`에서 `Flow<String>`을 받아 응답/처리 구현

이었습니다. [예시 코드](https://github.com/ku-ring/ktor-sse-test/tree/main/src/main/kotlin)도 작성해 두었습니다.

## 해결법?

일단 보시는 것처럼 suspend를 뗄 수는 없고, 대신 `sse()` 함수를 이용하여 로직을 람다식으로 받아야 할 것 같습니다.

2024-07-24 13:57 UTC, mwy3055 commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/sse/SSEDataSource.kt
> +}
그런데.. 서버에서 질문 횟수를 초과했을 때 json 응답을 보낼 수도 있다고 합니다. 즉 SSE와 json을 동시에 받을 수 있어야 하는데요

이건 다음 PR에서 대응하겠습니다

2024-07-24 14:56 UTC, x-0o0 commented on data/remote/src/test/java/com/ku_stacks/ku_ring/remote/SSERemoteDataSourceTest.kt
> +    }
와 짱 신기하다!

2024-07-25 13:24 UTC, mwy3055 commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/sse/SSEDataSource.kt
> +}
https://github.com/ku-ring/KU-Ring-Android/pull/277/commits/5332bec5fd84ca893c58a17c8b8675923c660f58 에서 `Flow<String>`을 반환하는 대신 콜백을 매개변수로 받는 방식을 구현했습니다.

2024-07-25 13:25 UTC, mwy3055 commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/sse/SSEDataSource.kt
> +}
https://github.com/ku-ring/KU-Ring-Android/pull/277/commits/f78279f653a5150ae6ae334825b84188ac8074ab 에서 content type에 따라 SSE와 json을 모두 처리하는 로직을 구현했습니다.

원래는 다음 PR에서 처리할 예정이었으나, 세부 구현은 여기서 마무리하고 다음 PR에서는 repository 로직에만 집중하려고 합니다.

2024-07-28 13:54 UTC, mwy3055 commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/sse/SSEDataSource.kt
> +}
https://github.com/ku-ring/KU-Ring-Android/pull/277/commits/4b424005d14faac6ea2cbc3be07fd15c570b6b61 에서 `Flow`를 반환하는 대신 콜백을 매개변수로 받도록 수정했습니다.

_cf. 쿠링봇 쿼리에 대한 응답은 항상 SSE 스트림으로 내려오는 것으로 결정되었습니다. Json 등 다른 포맷은 사용하지 않습니다._

2024-07-28 13:55 UTC, mwy3055 commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/sse/SSEDataSource.kt
> +}
순서대로 쿼리 내용이 범위를 벗어난 경우, 정상 응답, 요청 횟수를 초과했을 때의 응답입니다. 전부 수신 양호.

![image](https://github.com/user-attachments/assets/5d3efe62-d91c-4109-b07c-b83910621c83)

2024-07-31 13:33 UTC, l2hyunwoo approved these changes
리뷰 확인해주세요 :)

2024-07-31 13:33 UTC, l2hyunwoo commented on data/local/src/main/java/com/ku_stacks/ku_ring/local/entity/KuringBotMessageEntity.kt
> +    @PrimaryKey(autoGenerate = true) val id: Int,
```suggestion
    @PrimaryKey(autoGenerate = true) val id: Long,
```

로 바꾸는건 어떤가요?

2024-07-31 13:33 UTC, l2hyunwoo commented on data/local/src/main/java/com/ku_stacks/ku_ring/local/entity/KuringBotMessageEntity.kt
> +    @PrimaryKey(autoGenerate = true) val id: Int,
```suggestion
    @PrimaryKey(autoGenerate = true) val id: Long,
```

로 바꾸는건 어떤가요? 메시지여서 생각보다 금방 쌓일수도...?

2024-07-31 13:33 UTC, l2hyunwoo commented on data/local/src/main/java/com/ku_stacks/ku_ring/local/entity/KuringBotMessageEntity.kt
> +    @PrimaryKey(autoGenerate = true) val id: Int,
```suggestion
    @PrimaryKey(autoGenerate = true) val id: Long,
```

로 바꾸는건 어떤가요?

2024-07-31 13:33 UTC, l2hyunwoo commented on data/local/src/main/java/com/ku_stacks/ku_ring/local/room/KuringBotMessageDao.kt
> +    suspend fun clear()
엄 이 기능은 언제 사용할 일이 있을까요? 나름 유저의 정보가 담긴 저장소라 다 날려버리는 함수가 있다는게 좀 걱정이네유.

2024-07-31 13:33 UTC, l2hyunwoo commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/sse/SSERemoteDataSource.kt
> +        onData: (String) -> Unit,
onReceived 정도?

2024-07-31 13:33 UTC, l2hyunwoo commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/sse/SSERemoteDataSource.kt
> +    override suspend fun openKuringBotSSESession(
그리고 우리 리모트 프로토콜이 SSE로 항상 고정된건 아니어서 interface는 KuringBotClient/구현체는 KuringBotSSEClient 정도로 살짝 추상화보는건 어떨까요?

2024-07-31 13:33 UTC, l2hyunwoo commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/util/RemoteModule.kt
> +object RemoteModule {
Remote보단 Network가 좀 더 직관적일 것 같아요!

2024-07-31 13:33 UTC, l2hyunwoo commented on data/remote/src/test/java/com/ku_stacks/ku_ring/remote/SSERemoteDataSourceTest.kt
> +        assert(tokens.isNotEmpty())
isNotEmpty 대신 응답값을 비교하는건 어떨까요?

2024-08-01 01:02 UTC, mwy3055 commented on data/local/src/main/java/com/ku_stacks/ku_ring/local/entity/KuringBotMessageEntity.kt
> +    @PrimaryKey(autoGenerate = true) val id: Int,
월 2회 제한이 걸려있기도 하고, 나중에 좀 쌓인다 싶을 때 바꿔도 될 거 같아요. SQL 변경 없이 Entity만 바꾸면 되는 거라.

2024-08-01 01:04 UTC, mwy3055 commented on data/local/src/main/java/com/ku_stacks/ku_ring/local/room/KuringBotMessageDao.kt
> +    suspend fun clear()
CRUD 구현한 거긴 한데, 당분간 쓸 계획이 없으니 삭제하겠습니다

2024-08-01 01:18 UTC, mwy3055 commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/util/RemoteModule.kt
> +object RemoteModule {
동의합니다. 사실 모듈 이름이 `remote`라서 `RemoteModule`이라고 한 건데, 나중에 모듈 이름도 `network`로 바꾸는 게 좋겠네요

2024-08-01 01:22 UTC, mwy3055 commented on data/remote/src/test/java/com/ku_stacks/ku_ring/remote/SSERemoteDataSourceTest.kt
> +        assert(tokens.isNotEmpty())
응답값이 달라질 수 있다고 생각했는데, 쿼리가 고정된 이상 응답도 고정되어 바뀌지 않는다고 봐도 무방할 거 같네요

2024-08-01 01:24 UTC, mwy3055 commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/sse/SSERemoteDataSource.kt
> +        onData: (String) -> Unit,
https://github.com/ku-ring/KU-Ring-Android/pull/277/commits/c032ec031794492ff885bee7aabf8a703920c3f7 에서 수정했습니다

2024-08-01 01:25 UTC, mwy3055 commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/sse/SSERemoteDataSource.kt
> +    override suspend fun openKuringBotSSESession(
https://github.com/ku-ring/KU-Ring-Android/pull/277/commits/ca6354a855fe15ae6bc369e621aef81950451895 에서 수정했습니다. 좋은 추상화네요.

2024-08-01 01:25 UTC, mwy3055 commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/util/RemoteModule.kt
> +object RemoteModule {
https://github.com/ku-ring/KU-Ring-Android/pull/277/commits/e8f2bcec1a82b8b47e6db234d8b054983730cfcc 에서 수정했습니다

2024-08-01 01:25 UTC, mwy3055 commented on data/remote/src/test/java/com/ku_stacks/ku_ring/remote/SSERemoteDataSourceTest.kt
> +        assert(tokens.isNotEmpty())
https://github.com/ku-ring/KU-Ring-Android/pull/277/commits/a83849197461bbc579d5f6ad6d7907e555be381b 에서 수정했습니다

2024-08-01 01:44 UTC, merged

2024-08-01 03:50 UTC, l2hyunwoo commented on data/local/src/main/java/com/ku_stacks/ku_ring/local/room/KuringBotMessageDao.kt
> +    suspend fun clear()
그러면 @VisibleForTesting 어노테이션 붙여주는건 어떤가요?

2024-08-01 03:53 UTC, l2hyunwoo commented on data/remote/src/test/java/com/ku_stacks/ku_ring/remote/SSERemoteDataSourceTest.kt
> +        assert(tokens.isNotEmpty())
넵 👍🏻

2024-08-01 04:02 UTC, mwy3055 commented on data/local/src/main/java/com/ku_stacks/ku_ring/local/room/KuringBotMessageDao.kt
> +    suspend fun clear()
의견 감사합니다. 다음 PR에서 붙일게요

Sorry for mentinoning :)