feat: 도서관 남은 좌석 API 구현
ku-ring/KU-Ring-Android pull request #387
Opened 2024-11-19 05:50 UTC by boiledEgg-s

https://kuring.atlassian.net/browse/KURING-224?atlOrigin=eyJpIjoiNWVhZjQ3N2Y3YWVmNGMyZTg2Mjk0MTY0M2M5NDc3OGEiLCJwIjoiaiJ9

## 요약
- 도서관 남은 좌석을 가져오는 API을 프로젝트에서 사용하기 위해 Service, Client, Repository를 구현했습니다.
- 화면에서 테스트 해보기 어려워 테스트 코드도 구현했습니다! 근데 테스트 코드도 "300줄 미만 PR" 컨벤션에 포함이 되는건가요?
- Response를 다 쪼개서 구현을 해놨는데 이름 지어주는게 너무 어렵네요..

2024-11-20 10:58 UTC, mwy3055 requested changes
Retrofit response 클래스를 proguard-rules.pro의 30라인 밑에 **하나도 빠짐없이** 선언해 주세요. 난독화 때문에 release에서 제대로 파싱하지 못하는 경우가 많았습니다.

그 외에는 코멘트 가볍게 읽어보시면 되겠습니다.

2024-11-20 10:58 UTC, mwy3055 commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/library/LibraryService.kt
> +    ): LibrarySeatResponse
base url에 `1/`까지는 포함해도 됐을 것 같다는 생각이...? 그러면 `@GET("seat-rooms")`가 되겠죠

사실 기존 쿠링 API에도 적용되는 내용입니다. 원래는 API v1과 v2가 있었는데, 이제 v2만 쓰고 있기 때문에 base url에 `v2`까지 포함시켜도 되는 거죠. 이건 나중에 ktor 리팩토링할 때 하겠습니다 (리팩토링을 한다면)

2024-11-20 10:58 UTC, mwy3055 commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/library/request/LibrarySeatRequest.kt
> +}
오... 상수...

2024-11-20 10:58 UTC, mwy3055 commented on data/library/build.gradle.kts
> +}
이거 이해하기 어렵지 않았나요?

2024-11-20 10:58 UTC, mwy3055 commented on data/domain/src/main/java/com/ku_stacks/ku_ring/domain/LibraryRoom.kt
> +    val availableSeats: Int
trailing comma?

2024-11-20 10:58 UTC, mwy3055 commented on data/library/src/main/java/com/ku_stacks/ku_ring/library/repository/LibraryRepositoryImpl.kt
> +    }
예외처리 굿

2024-11-20 15:45 UTC, boiledEgg-s commented on data/library/build.gradle.kts
> +}
사실 아직 제대로 이해하진 못했어요,,
저 플러그인들에 필요한 라이브러리들이 있겠거니 해서 일단 넣었습니다😅

2024-11-21 02:02 UTC, l2hyunwoo commented on data/library/build.gradle.kts
> +}
ㅋㅋㅋㅋㅋ이것도 강의 해줄게요

2024-11-21 02:03 UTC, l2hyunwoo commented on data/library/build.gradle.kts
> +    setNameSpace("library")
이거 data.library가 낫지 않을까 생각합니다.

2024-11-21 02:10 UTC, l2hyunwoo commented on data/library/src/main/java/com/ku_stacks/ku_ring/library/repository/LibraryRepositoryImpl.kt
> +    }
그런데 여기서 예외처리하는게 맞을까요? UI쪽에서 에러 캐치를 해야 특정 Exception에 대응하는 화면을 만들 수 있는 등의 처리를 할 수 있을 것 같아서요.

2024-11-21 02:11 UTC, l2hyunwoo commented on data/library/src/test/java/com/ku_stacks/ku_ring/library/LibraryRepositoryTest.kt
> +        Mockito.`when`(client.fetchRoomSeatStatus()).thenReturn(mockLibraryStatus)
굳이 Mock을 사용할 필요가 있을까요? 인터페이스 다형성을 활용해보면 좋을 것 같아요

2024-11-21 02:14 UTC, l2hyunwoo commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/library/response/LibraryRoomBranchResponse.kt
> +)
이거 난독화 걸리면 name 빼고 다른 프로퍼티는 난독화 안전하지 않습니다. 혹시 모르니 수정해주시는걸 권장합니다.

2024-11-21 02:15 UTC, l2hyunwoo commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/util/NetworkModule.kt
> +            .addConverterFactory(GsonConverterFactory.create())
@mwy3055 null 안정성 생각하면 kotlinx.serialization 적용하는것도...?

2024-11-21 02:15 UTC, l2hyunwoo commented on data/remote/src/test/java/com/ku_stacks/ku_ring/remote/LibraryServiceTest.kt
이 테스트는 작성한 의도가 있을까요?

2024-11-21 12:16 UTC, mwy3055 commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/util/NetworkModule.kt
> +            .addConverterFactory(GsonConverterFactory.create())
사실 null 때문에 [티켓](https://kuring.atlassian.net/browse/KURING-27?atlOrigin=eyJpIjoiMmIyODYzMTZiZTFjNGQzOTg0YWQ3MjE2NTAzZjFjOGYiLCJwIjoiaiJ9)도 만들긴 했습니다. 오래전부터 인지하고 있던 문제였는데요

kotlinx.serialization 좀 찾아보니까 서버에서 값이 안 오면 변환할 때 exception이 나는 거 같은데, 예측할 수 없는 NPE보다는 이게 나은 거 같네요. 라이브러리 바꿀 게 많네요 ㅋㅋ

2024-11-21 12:18 UTC, mwy3055 commented on data/library/src/main/java/com/ku_stacks/ku_ring/library/repository/LibraryRepositoryImpl.kt
> +    }
음.. 생각해 보니 그렇네요. 여기서는 exception을 그대로 던지거나, exception을 잡고 `LibraryException` 같은 커스텀 예외를 반환하는 게 나을수도 있겠네요

2024-11-21 13:22 UTC, boiledEgg-s commented on data/library/src/test/java/com/ku_stacks/ku_ring/library/LibraryRepositoryTest.kt
> +        Mockito.`when`(client.fetchRoomSeatStatus()).thenReturn(mockLibraryStatus)
제가 테스트 코드 작성이 아직 미흡해서 기존 테스트 코드를 좀 차용했습니다..
추후에 좀 더 괜찮은 방법으로 테스트 코드를 작성해보도록 할게요!

2024-11-21 14:12 UTC, boiledEgg-s commented on data/remote/src/test/java/com/ku_stacks/ku_ring/remote/LibraryServiceTest.kt
이 테스트 코드도 기존 코드를 차용한 것 입니다..
제가 이해한 테스트 코드 진행 순서인데, 이게 맞을까요?

1. initService에서 createService 함수를 통해 테스트용 서비스 변수를 초기화
2. @test 함수에서 enqueueResponse로 service의 함수를 호출했을 때 반환할 응답으로 json 파일을 지정
3. mockWebServer의 takeRequest()를 통해 service가 의도대로 동작했는지 확인
4. assert로 반환된 값이랑 예상 값이랑 비교

2024-11-21 15:33 UTC, l2hyunwoo commented on data/remote/src/test/java/com/ku_stacks/ku_ring/remote/LibraryServiceTest.kt
mockWebServer에서 response를 테스트 하는것은 저희가 직접 정해주는 값을 넣고 그 값이 객체로 잘 역직렬화되는지를 확인하는 것과 같은데, 이런 테스트를 작성해서 얻을 수 있는 효험이 어떤 것이 있을지 생각해보면 좋을 것 같아요. 추가로 리스폰스가 변경이 되면 json 파일도 변경이 되어야 하는 등 유지보수를 해야하는데 그걸 감안하더라도 의미가 있는지까지 같이!

2024-11-21 15:33 UTC, l2hyunwoo commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/util/NetworkModule.kt
> +            .addConverterFactory(GsonConverterFactory.create())
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

이것도 차근차근 해봅시다(그리고 하루컷 나고 그러는거 아닌가)

2024-11-21 15:34 UTC, l2hyunwoo commented on data/library/src/test/java/com/ku_stacks/ku_ring/library/LibraryRepositoryTest.kt
> +        Mockito.`when`(client.fetchRoomSeatStatus()).thenReturn(mockLibraryStatus)
넵 좋습니다.

2024-11-21 15:34 UTC, l2hyunwoo commented on data/library/build.gradle.kts
> +    setNameSpace("library")
아 여기 nia하고 비슷한 구조구나, 이대로 가도 좋을 것 같아요

2024-11-23 08:15 UTC, mwy3055 approved these changes
이정도면 괜찮은 것 같습니다 :+1:

2024-11-23 08:15 UTC, mwy3055 commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/library/response/LibrarySeatResponse.kt
>  )
`@SerializedName`을 자동으로 붙여주는 gradle 플러그인을 만들어 보면..? 그냥 아이디어입니다 ㅎㅎ

2024-11-28 05:27 UTC, l2hyunwoo commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/library/di/LibraryModule.kt
> +        = retrofit.create(LibraryService::class.java)
```suggestion
        = retrofit.create()
```

이렇게 적어도 됩니다ㅋㅋㅋㅋ

2024-11-28 05:27 UTC, l2hyunwoo commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/library/di/LibraryModule.kt
> +        = LibraryClient(libraryService)
이건 굳이 작성 안해주셔도 될거에요

2024-11-28 05:28 UTC, l2hyunwoo commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/library/request/LibrarySeatRequest.kt
> +}
이 오브젝트는 따로 작성하신 이유가 있나요?

2024-11-28 05:29 UTC, l2hyunwoo approved these changes
고생하셨습니다.

2024-11-28 07:01 UTC, boiledEgg-s commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/library/request/LibrarySeatRequest.kt
> +}
요청에 필요한 상수들이 한 군데에서 관리되고, 무슨 역할인지 명확히 알 수 있으면 좋을 것 같아서 object로 작성했습니다!

2024-11-28 07:06 UTC, boiledEgg-s commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/library/di/LibraryModule.kt
> +        = LibraryClient(libraryService)
아 Client가 추상체와 구현체로 나뉘지 않아서 필요가 없겠네요

2024-11-28 07:52 UTC, merged