feat: 도서관 남은 좌석 UI 구현
ku-ring/KU-Ring-Android pull request #391
Opened 2024-12-09 04:33 UTC by boiledEgg-s

https://kuring.atlassian.net/browse/KURING-226?atlOrigin=eyJpIjoiYTlhZWM5YjkwMzllNDk1NDgwZjY2ODRiNjc1Mzg1OTQiLCJwIjoiaiJ9

## 요약

- 도서관 남은 좌석 UI 구현
- Navigator와 Manifest에 Activity 등록
- 화면 이동 로직 및 뷰모델, 상태관리 미구현 (해당 PR을 머지한 후 작업할 예정)
- 하단 영상은 프리뷰 인터렉티브 모드로 촬영
<video src="https://github.com/user-attachments/assets/6ef1fe98-8077-40f6-b224-1a16a8b8c285" width = 300/>

2024-12-11 13:06 UTC, mwy3055 requested changes
Request changes이긴 한데, UI 구현 자체에는 큰 문제 없습니다. 가볍게 읽어주세요.

2024-12-11 13:06 UTC, mwy3055 commented on feature/library/src/main/java/com/ku_stacks/ku_ring/library/compose/LibrarySeatScreen.kt
> +    seatStatus: List<LibraryRoom>,
`seatStatus`가 첫 번째 매개변수로 오는게 적절하지 않을까요?

2024-12-11 13:06 UTC, mwy3055 commented on feature/library/src/main/java/com/ku_stacks/ku_ring/library/compose/component/SeatStatusReloadFab.kt
> +
공백 1줄로 줄여주세요

2024-12-11 13:06 UTC, mwy3055 commented on feature/library/src/main/java/com/ku_stacks/ku_ring/library/compose/component/SeatStatusReloadFab.kt
> +
여기도요. 공백이 불필요하게 있을 필요는 없어 보입니다

2024-12-13 00:35 UTC, l2hyunwoo commented on core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/progress/CircularProgressBar.kt
> +fun CircularProgressBar(
이건 필요하긴 하니까....

2024-12-13 00:36 UTC, l2hyunwoo commented on core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/topbar/NavigateUpTopBar.kt
> +                onClick = onNavigationIconClick
noClickable 같은데 TopBar 네비게이션 아이콘에 리플이 없어도 되려나요...?

2024-12-13 00:38 UTC, l2hyunwoo commented on feature/library/src/main/java/com/ku_stacks/ku_ring/library/compose/LibrarySeatScreen.kt
> +            onStatusReloadButtonClick = { isLoading = !isLoading},
```suggestion
            onStatusReloadButtonClick = { isLoading = !isLoading },
```

2024-12-13 00:40 UTC, l2hyunwoo commented on feature/library/src/main/java/com/ku_stacks/ku_ring/library/compose/component/SeatStatusGroup.kt
> +                    .size(108.dp),
서큘러 인디케이터는 태블릿이나 모바일이나 거의 비슷한 사이즈로 운용되어서 괜찮을 수도 있을듯합니다...?!!

2024-12-13 00:42 UTC, l2hyunwoo commented on feature/library/src/main/java/com/ku_stacks/ku_ring/library/LibrarySeatActivity.kt
> +}
enableEdgeToEdge 없어도 되나요?

2024-12-17 15:01 UTC, boiledEgg-s commented on core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/progress/CircularProgressBar.kt
> +fun CircularProgressBar(
너무 베이직한 컴포넌트라 일단 `designsystem`에 들어가는게 맞다고 판단했어요ㅎㅎ

2024-12-18 09:39 UTC, boiledEgg-s commented on feature/library/src/main/java/com/ku_stacks/ku_ring/library/compose/component/SeatStatusGroup.kt
> +                fontFamily = Pretendard,
부분부분 빼먹은데가 있는 것 같네요,, 다른 곳도 확인해볼게요!

2024-12-18 09:43 UTC, boiledEgg-s commented on feature/library/src/main/java/com/ku_stacks/ku_ring/library/compose/component/SeatStatusGroup.kt
> +                    .size(108.dp),
패딩을 활용하더라도 하드코딩 문제는 남는다고 생각했습니다,,  패딩 값도 크더라구요

2024-12-18 09:44 UTC, boiledEgg-s commented on core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/topbar/NavigateUpTopBar.kt
다른 코드를 왠만하면 건드리지 않으려고 했는데 이 부분은 나중에 수정하는게 좋겠네요

2024-12-18 09:48 UTC, boiledEgg-s commented on core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/topbar/NavigateUpTopBar.kt
> +                onClick = onNavigationIconClick
다른 부분들을 확인해보니까 리플이 있네요? 이건 일관성을 위해 삭제하도록 하겠습니다!

2024-12-18 10:08 UTC, boiledEgg-s commented on feature/library/src/main/java/com/ku_stacks/ku_ring/library/LibrarySeatActivity.kt
> +}
추가했습니다!

2024-12-19 07:50 UTC, boiledEgg-s commented
> 👍
> 
> 종강하셨나요? ㅎㅎ

ㅎㅎ 넵

2024-12-21 00:16 UTC, merged