kuring-227 드래그 LazyList, 카테고리 순서 DB 구현
ku-ring/KU-Ring-Android pull request #404
Opened 2024-12-25 08:49 UTC by mwy3055

https://kuring.atlassian.net/browse/KURING-227?atlOrigin=eyJpIjoiODliNjhlODc0ZGRiNDJmZTgyY2M3MTA5NzUwNzVmYzUiLCJwIjoiaiJ9

## 요약

카테고리 순서 변경의 첫 번째 작업으로, 드래그 가능한 리스트 `DraggableLazyColumn`과 카테고리 순서 DB를 구현했습니다.

* `DraggableLazyColumn`은 [이 글](https://medium.com/@hyeonseosong733/compose-drag-and-drop-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0-1deb3c5c47da)을 많이 참고했습니다. 코드를 자세히 보기는 조금 어려울 수도 있습니다. 프리뷰를 참고하여 보시면 됩니다.
* 카테고리 순서 DB는 entity 정의, Dao 정의, 도메인 객체 추가, `UserRepository`에 기능 노출 순서대로 구현되어 있습니다. 매우 전형적인 흐름이므로 리뷰하시기 한결 쉬울 것 같습니다.

2024-12-25 12:04 UTC, l2hyunwoo commented on core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/dragdrop/DragDropState.kt
> +    val state = remember(lazyListState) {
Q) 이거 onMove 변경될때에도 state 값 갱신해야하지 않을까요?

2024-12-25 12:09 UTC, l2hyunwoo commented on core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/dragdrop/DragDropUtil.kt
> +    this.add(to, element)
여기에서만 쓰이는거라면 internal 붙여도 될 듯 합니다.

2024-12-25 12:13 UTC, l2hyunwoo requested changes
두개의 PR이 하나의 PR로 합쳐진 것 같은데...

- DraggableLazyColumn
- CategoryOrder DB 구현

이렇게 두개로 쪼개도 괜찮았을듯합니다.

2024-12-26 11:58 UTC, mwy3055 commented on core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/dragdrop/DragDropState.kt
> +    val state = remember(lazyListState) {
실질적으로 onMove가 바뀔 일은 별로 없겠지만, 일단 추가하는 게 맞는 것 같아 수정했습니다.

https://github.com/ku-ring/KU-Ring-Android/pull/404/commits/3a087871d29d18ddb80a7af0611c84083e180cfa

2024-12-26 11:59 UTC, mwy3055 commented on core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/dragdrop/DragDropUtil.kt
> +    this.add(to, element)
여기에서만 쓰일 것 같아서 internal 붙였습니다.

https://github.com/ku-ring/KU-Ring-Android/pull/404/commits/b57606505afc2e2acadc4b25b05537ecbdeb9fa8

2024-12-26 11:59 UTC, mwy3055 commented
컨플릭은 따로 보겠습니다. 근데 그냥 import 이슈네요

2024-12-29 17:40 UTC, boiledEgg-s commented
확실히 리드님의 코드는 다르네요,, 킹우영👑

2025-02-09 15:47 UTC, l2hyunwoo commented on core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/dragdrop/DragDropState.kt
> +}
You are good! 참고로 람다는 이제 remember 강제로 씌워지기 때문에 이렇게 만들어도 된답니다!

2025-02-09 15:48 UTC, l2hyunwoo approved these changes
👍🏻

2025-02-10 07:59 UTC, boiledEgg-s approved these changes
다시 어프드리는걸 깜박했네요.. 고생하셨습니다!

2025-03-23 10:51 UTC, mwy3055 commented
엥 이거 뭐지 ㅋㅋㅋ 머지합니다

2025-03-23 10:52 UTC, merged